# Generated by Django 5.2.2 on 2025-06-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recipient_account', models.CharField(max_length=50)),
                ('sig_p', models.TextField()),
                ('sig_s', models.TextField()),
                ('q_p', models.TextField()),
                ('q_s', models.TextField()),
                ('bank_response', models.TextField(blank=True)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.securecipheruser')),
            ],
        ),
    ]
